export const IS_LOGGED_IN = "IS_LOGGED_IN";
export const TOKENS = "TOKENS";
export const RETAILER_DETAILS = "RETAILER_DETAILS";
export const NEW_CART = "NEW_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_ADD = "UPDATE_CART_ADD";
export const UPDATE_CART_SUBTRACT = "UPDATE_CART_SUBTRACT";
export const CART_CHANGE_QUANTITY = "CART_CHANGE_QUANTITY";
export const SCREEN = "SCREEN";
export const VERIFICATION_STATUS = "VERIFICATION_STATUS";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const COMPANY_FILTER_ADD="COMPANY_FILTER_ADD";
export const COMPANY_FILTER_REMOVE="COMPANY_FILTER_REMOVE";
export const BRAND_FILTER_ADD="BRAND_FILTER_ADD";
export const BRAND_FILTER_REMOVE="BRAND_FILTER_REMOVE";
export const PRODUCT_GROUP_FILTER_ADD="PRODUCT_GROUP_FILTER_ADD";
export const PRODUCT_GROUP_FILTER_REMOVE="PRODUCT_GROUP_FILTER_REMOVE";
export const RESET_FILTERS="RESET_FILTERS";
export const SELECT_FILTER_TYPE="SELECT_FILTER_TYPE";
export const SELECT_DISTRIBUTOR="SELECT_DISTRIBUTOR";
export const MARGIN_FILTERS = "MARGIN_FILTERS";
export const CHANGE_LOT_SIZE = "CHANGE_LOT_SIZE";



